import { Property } from './types';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Modern Luxury Villa',
    description: 'A stunning modern villa with panoramic views, featuring high-end finishes and a private infinity pool. Perfect for luxury living.',
    price: 1250000,
    type: 'sale',
    category: 'home',
    location: 'Beverly Hills, CA',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/be254f08-06fc-4c40-ab3e-bfe0e3cee057/luxury-villa-1-795f8123-1779451068243.webp',
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    features: ['Swimming Pool', 'Smart Home', 'Wine Cellar', 'Garden'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Cozy Downtown Apartment',
    description: 'Modern apartment in the heart of the city. Features floor-to-ceiling windows and premium appliances.',
    price: 3500,
    type: 'rent',
    category: 'home',
    location: 'Downtown Manhattan, NY',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/be254f08-06fc-4c40-ab3e-bfe0e3cee057/modern-apartment-1-0d693a5d-1779451066587.webp',
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    features: ['Gym Access', 'Concierge', 'Rooftop Deck'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Prime Development Land',
    description: 'A large parcel of land ready for residential or agricultural development. Stunning natural surroundings.',
    price: 450000,
    type: 'sale',
    category: 'land',
    location: 'Asheville, NC',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/be254f08-06fc-4c40-ab3e-bfe0e3cee057/vacant-land-1-a5a5512a-1779451067959.webp',
    area: 43560, // 1 acre
    features: ['Water Access', 'Road Frontage', 'Utilities Ready'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Suburban Family Home',
    description: 'Charming family home in a quiet neighborhood. Spacious backyard and updated kitchen.',
    price: 525000,
    type: 'sale',
    category: 'home',
    location: 'Austin, TX',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/be254f08-06fc-4c40-ab3e-bfe0e3cee057/suburban-house-1-2c0a9d5e-1779451068244.webp',
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    features: ['Backyard', 'Garage', 'Near Schools'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Modern Office Space',
    description: 'Flexible office layout in a prime commercial building. High-speed internet and conference facilities.',
    price: 12000,
    type: 'rent',
    category: 'commercial',
    location: 'Seattle, WA',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/be254f08-06fc-4c40-ab3e-bfe0e3cee057/office-building-1-4882d9dd-1779451067959.webp',
    area: 5000,
    features: ['High-speed Internet', 'Security', 'Parking'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Beachfront Paradise Cottage',
    description: 'Wake up to the sound of waves in this beautiful beachfront cottage. Perfect for vacations or short-term rentals.',
    price: 850000,
    type: 'sale',
    category: 'home',
    location: 'Maui, HI',
    image: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/be254f08-06fc-4c40-ab3e-bfe0e3cee057/beach-cottage-1-f5719c22-1779451067958.webp',
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    features: ['Ocean View', 'Private Beach Access', 'Deck'],
    createdAt: new Date().toISOString(),
  },
];